import grpc
import subprocess
import sys
import os
import time
import base64
from concurrent import futures
from jupyter_client import KernelManager

# Import generated classes
# Note: These will be generated by the user or build script
# Import generated classes
import sidecar_pb2 as sidecar_pb2
import sidecar_pb2_grpc as sidecar_pb2_grpc

class SidecarServicer(sidecar_pb2_grpc.SidecarServicer):
    def __init__(self):
        self.km = KernelManager(kernel_name='python3')
        self.km.start_kernel()
        self.kc = self.km.client()
        self.kc.start_channels()
        # Wait for kernel to be ready
        self.kc.wait_for_ready(timeout=60)
        print("Kernel ready.")

    def Execute(self, request, context):
        code = request.code
        print(f"Executing code: {code[:50]}...")
        
        # Execute the code
        msg_id = self.kc.execute(code)
        
        stdout = []
        stderr = []
        images = []
        
        while True:
            try:
                msg = self.kc.get_iopub_msg(timeout=10)
                msg_type = msg['header']['msg_type']
                content = msg['content']
                
                if msg_type == 'stream':
                    if content['name'] == 'stdout':
                        stdout.append(content['text'])
                    elif content['name'] == 'stderr':
                        stderr.append(content['text'])
                elif msg_type == 'display_data' or msg_type == 'execute_result':
                    if 'data' in content:
                        data = content['data']
                        if 'image/png' in data:
                            images.append(data['image/png'])
                elif msg_type == 'status' and content['execution_state'] == 'idle':
                    break
            except Exception as e:
                print(f"Error getting message: {e}")
                break
                
        return sidecar_pb2.ExecuteResponse(
            stdout="".join(stdout),
            stderr="".join(stderr),
            images=images
        )

    def stop(self):
        self.kc.stop_channels()
        self.km.shutdown_kernel()

def serve():
    server = grpc.server(futures.ThreadPoolExecutor(max_workers=10))
    servicer = SidecarServicer()
    sidecar_pb2_grpc.add_SidecarServicer_to_server(servicer, server)
    server.add_insecure_port('[::]:50051')
    server.start()
    print("Sidecar server started on port 50051.")
    try:
        while True:
            time.sleep(86400)
    except KeyboardInterrupt:
        servicer.stop()
        server.stop(0)

if __name__ == '__main__':
    serve()
